services:
  db:
    image: mysql:9.5
    environment:
      MYSQL_ROOT_PASSWORD: "janeausten123"
      MYSQL_DATABASE: "theinfinitelibrary"
  frontend:
    build: ./theinfinitelibrary-frontend
    image: theinfinitelibrary-frontend:1.0
    ports:
      - 3000:3000
  backend:
    build: ./theinfinitelibrary-backend
    image: theinfinitelibrary-backend:1.0
    ports: 
      - 8000:8000
    environment:
      - DB_USER=root
      - DB_PASSWORD=janeausten123
      - DB_NAME=theinfinitelibrary
      - DB_HOST=db
    depends_on:
      - db
  
  